services:
  frontend:
    build:
      args:
        HOST: testing.aquapants.org
        PORT: 80
      context: .
      dockerfile: Dockerfile
    image: us-central1-docker.pkg.dev/aquapants-website/website/site-testing
    container_name: aquapants-website-frontend
    restart: always
    volumes:
      - ./site/:/usr/share/nginx/html
    ports:
      - 3050:80