services:
  frontend:
    build:
      args:
        HOST: aquapants-local-testing.org
        PORT: 80
      context: .
      dockerfile: Dockerfile
    image: silly-willy:latest
    container_name: aquapants-website-frontend
    restart: always
    volumes:
      - ./site/:/usr/share/nginx/html
    ports:
      - 3050:80
