name: ci

on:
  pull_request:
    branches: main

jobs:
  prettier:
    name: 💅 prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}

      - name: yarn install
        run: yarn install

      - name: Check formatting
        run: |
          yarn prettier --check .
